Repository udistrital/parametros_gobierno, pull requests merged in 2019-07, with the labels that each got.

#3 Creación de API CRUD para consulta de tablas RUP-SNIES #2
  conf/app.conf
  controllers/object.go
  controllers/user.go
  database/migrations/20190716_101001_crear_schema.go
  database/migrations/20190716_101002_crear_tabla_area_conocimiento.go
  database/migrations/20190716_101003_crear_tabla_nucleo_basico_conocimiento.go
  database/migrations/20190716_101004_crear_tabla_rup_tipo_especialidad.go
  database/migrations/20190716_101005_crear_tabla_rup_especialidad.go
  database/migrations/20190716_101006_crear_tabla_rup_grupo.go
  database/migrations/20190716_101007_crear_llaves_foraneas.go
  main.go
  models/object.go
  models/user.go
  routers/router.go
  sql/esquema_parametros_gobierno.sql
  tests/default_test.go
Labels: good first issue

#8 Se agrega variable de entorno para esquemas #2
  conf/app.conf
Labels: bug

#9 Se corrige ariable de entorno para esquemas #2
  conf/app.conf
Labels: bug

#10 se corrige variable de entorno de puerto #2
  conf/app.conf
Labels: bug

#11 se agrega imagen version final de esquema parametros_gobierno con aju…
  sql/imagen_parametros_gubernamentales.png
Labels: documentation

#12 se corrige imagen version final de esquema parametros_gobierno con aj…
  sql/imagen_parametros_gubernamentales.png
  sql/parametros_gubernamentales.png
Labels: documentation

#13 se añaden archivos necesarios para despliegue en AWS, ambientes test …
  .dockerignore
  .drone.yml
  Dockerfile
  entrypoint.sh
Labels: enhancement

#14 A rama test para despliegues en AWS
  .dockerignore
  .drone.yml
  .gitignore
  Dockerfile
  conf/app.conf
  controllers/area_conocimiento.go
  controllers/nucleo_basico_conocimiento.go
  controllers/rup_especialidad.go
  controllers/rup_grupo.go
  controllers/rup_tipo_especialidad.go
  database/migrations/20190716_101001_crear_schema.go
  database/migrations/20190716_101002_crear_tabla_area_conocimiento.go
  database/migrations/20190716_101003_crear_tabla_nucleo_basico_conocimiento.go
  database/migrations/20190716_101004_crear_tabla_rup_tipo_especialidad.go
  database/migrations/20190716_101005_crear_tabla_rup_especialidad.go
  database/migrations/20190716_101006_crear_tabla_rup_grupo.go
  database/migrations/20190716_101007_crear_llaves_foraneas.go
  entrypoint.sh
  main.go
  models/area_conocimiento.go
  models/nucleo_basico_conocimiento.go
  models/rup_especialidad.go
  models/rup_grupo.go
  models/rup_tipo_especialidad.go
  routers/commentsRouter_controllers.go
  routers/router.go
  sql/esquema_parametros_gobierno.sql
  sql/parametros_gubernamentales.png
  swagger/favicon-16x16.png
  swagger/favicon-32x32.png
  swagger/index.html
  swagger/oauth2-redirect.html
  swagger/swagger-ui-bundle.js
  swagger/swagger-ui-bundle.js.map
  swagger/swagger-ui-standalone-preset.js
  swagger/swagger-ui-standalone-preset.js.map
  swagger/swagger-ui.css
  swagger/swagger-ui.css.map
  swagger/swagger-ui.js
  swagger/swagger-ui.js.map
  swagger/swagger.json
  swagger/swagger.yml
  tests/default_test.go
Labels: enhancement

#15 prueba para ejecutar CI #2
  main.go
Labels: bug

#16 prueba para ejecutar CI #2
  main.go
Labels: bug

#17 se modifica drone.yml, cambiando ramas con nombre develop a test #2
  .drone.yml
Labels: bug

#18 se modifica drone.yml, cambiando ramas con nombre develop a test #2
  .drone.yml
Labels: bug

#19 :tropical_fish: Junto a @mariaalejandra9404 Se crea nuevo archivo mig…
  database/migrations/20190729_111601_eliminar_constraint.go
  models/rup_grupo.go
  sql/esquema_parametros_gobierno.sql
  sql/parametros_gubernamentales.png
Labels: bug

#20 Se crea archivo migrations para cambiar el tamaño de una c…
  database/migrations/20190729_111602_cambiar_size_columna.go
  sql/esquema_parametros_gobierno.sql
Labels: bug
